version: '3'

services:
  codeana:
    build:
      context: .
      dockerfile: Dockerfile
    image: codeana:latest
    container_name: codeana
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    privileged: true
    tty: true
    stdin_open: true 